const REMOVE = 'REMOVE';
const SELECT = 'SELECT';
const UNSELECT = 'UNSELECT';
const ENTER_TODO = 'Enter To Do';
const REMOVE_SELECTED_TODO = 'REMOVE SELECTED TODOS';

export { REMOVE, SELECT, UNSELECT, ENTER_TODO, REMOVE_SELECTED_TODO };
